import { useState, useEffect } from "react";
import { auth, db } from "../services/firebase";
import { addDoc, collection, getDocs, limit, query, serverTimestamp, where } from "firebase/firestore";

export function Shell({title,icon,children,onBack}){return <main className="page"><header><button onClick={onBack}>←</button><h2>{title}</h2><span/></header><section className="card"><div className="service-icon">{icon}</div>{children}</section></main>}

export function SendMoney({user,onBack}){const [phone,setPhone]=useState(""),[amount,setAmount]=useState(""),[message,setMessage]=useState(""),[loading,setLoading]=useState(false);
const send=async()=>{setMessage("");const p=phone.replace(/\D/g,""),a=Number(amount);if(!/^09\d{9}$/.test(p))return setMessage("Enter a valid 11-digit PH number.");if(!(a>0))return setMessage("Enter a valid amount.");if(a>Number(user.balance||0))return setMessage("Insufficient balance.");if(p===user.phone)return setMessage("You cannot send money to yourself.");setLoading(true);try{const q=query(collection(db,"users"),where("phone","==",p),limit(1));const s=await getDocs(q);if(s.empty)return setMessage("Recipient is not registered.");const r=s.docs[0];await addDoc(collection(db,"transferRequests"),{senderUid:auth.currentUser.uid,senderPhone:user.phone,senderName:user.name||"PeraGo User",recipientUid:r.id,recipientPhone:p,recipientName:r.data().name||"PeraGo User",amount:a,status:"pending",createdAt:serverTimestamp()});setPhone("");setAmount("");setMessage("Transfer request sent successfully. Balance movement is handled by the trusted backend.");}catch(e){setMessage(e.message)}finally{setLoading(false)}};return <Shell title="Send Money" icon="↗" onBack={onBack}><h1>Send Money</h1><p>Transfer money to another PeraGo user.</p><label>Recipient Mobile Number</label><input value={phone} maxLength="11" inputMode="numeric" placeholder="09XXXXXXXXX" onChange={e=>setPhone(e.target.value.replace(/\D/g,""))}/><label>Amount</label><div className="amount"><b>₱</b><input type="number" min="1" value={amount} placeholder="0.00" onChange={e=>setAmount(e.target.value)}/></div><button onClick={send} disabled={loading}>{loading?"Sending...":"Send Money"}</button>{message&&<div className="message">{message}</div>}</Shell>}

export function ReceiveMoney({user,onBack}){const copy=()=>navigator.clipboard?.writeText(user.phone);return <Shell title="Receive Money" icon="↙" onBack={onBack}><h1>Receive Money</h1><p>Share your PeraGo mobile number with the sender.</p><div className="receive-box"><span>Your PeraGo Number</span><strong>{user.phone}</strong><small>{user.name}</small></div><button onClick={copy}>Copy Number</button><p className="hint">QR receiving can be added next.</p></Shell>}
export function CashIn({onBack}){const [amount,setAmount]=useState(""),[method,setMethod]=useState("Bank"),[msg,setMsg]=useState("");return <Shell title="Cash In" icon="+" onBack={onBack}><h1>Cash In</h1><p>Add funds to your PeraGo wallet.</p><label>Amount</label><input type="number" min="1" placeholder="₱0.00" value={amount} onChange={e=>setAmount(e.target.value)}/><label>Method</label><select value={method} onChange={e=>setMethod(e.target.value)}><option>Bank</option><option>GCash</option><option>PayMaya</option><option>Over-the-counter</option></select><button onClick={()=>setMsg("Cash-in request prepared. Connect a payment provider to move real funds.")}>Continue</button>{msg&&<div className="message">{msg}</div>}</Shell>}
export function CashOut({onBack}){const [amount,setAmount]=useState(""),[method,setMethod]=useState("Bank"),[msg,setMsg]=useState("");return <Shell title="Cash Out" icon="−" onBack={onBack}><h1>Cash Out</h1><p>Withdraw from your PeraGo wallet.</p><label>Amount</label><input type="number" min="1" placeholder="₱0.00" value={amount} onChange={e=>setAmount(e.target.value)}/><label>Destination</label><select value={method} onChange={e=>setMethod(e.target.value)}><option>Bank</option><option>GCash</option><option>PayMaya</option></select><button onClick={()=>setMsg("Cash-out request prepared. Connect a payout provider to move real funds.")}>Continue</button>{msg&&<div className="message">{msg}</div>}</Shell>}
export function Bills({onBack}){const [msg,setMsg]=useState("");return <Shell title="Pay Bills" icon="▤" onBack={onBack}><h1>Pay Bills</h1><p>Select a biller to continue.</p><div className="option-grid">{["Electricity","Water","Internet","Mobile Postpaid","Government"].map(x=><button key={x} onClick={()=>setMsg(`${x} selected. Biller integration can be connected next.`)}>{x}</button>)}</div>{msg&&<div className="message">{msg}</div>}</Shell>}
export function BuyLoad({onBack}){const [phone,setPhone]=useState(""),[msg,setMsg]=useState("");return <Shell title="Buy Load" icon="▣" onBack={onBack}><h1>Buy Load</h1><p>Choose a load package.</p><label>Mobile Number</label><input value={phone} maxLength="11" inputMode="numeric" placeholder="09XXXXXXXXX" onChange={e=>setPhone(e.target.value.replace(/\D/g,""))}/><div className="option-grid">{["₱20 Load","₱50 Load","₱100 Load","Data 7 Days"].map(x=><button key={x} onClick={()=>setMsg(`${x} selected. Load provider integration can be connected next.`)}>{x}</button>)}</div>{msg&&<div className="message">{msg}</div>}</Shell>}
export function EMoney({onBack}){const [msg,setMsg]=useState("");return <Shell title="eMoney" icon="₱" onBack={onBack}><h1>eMoney</h1><p>Manage supported digital-money services.</p><div className="option-grid">{["Send eMoney","Receive eMoney","Convert","eMoney History"].map(x=><button key={x} onClick={()=>setMsg(`${x} selected.`)}>{x}</button>)}</div>{msg&&<div className="message">{msg}</div>}</Shell>}
export function More({onBack,onNavigate}){return <Shell title="More" icon="•••" onBack={onBack}><h1>More</h1><p>Additional PeraGo features.</p><div className="option-grid"><button onClick={()=>onNavigate("profile")}>Profile</button><button onClick={()=>onNavigate("activity")}>Activity</button><button>Security</button><button>Help & Support</button><button>Settings</button></div></Shell>}

export function Profile({user,onBack,onLogout}){return <Shell title="Profile" icon="●" onBack={onBack}><div className="profile-avatar">{user.name?.charAt(0)?.toUpperCase()||"P"}</div><h1>{user.name||"PeraGo User"}</h1><p>{user.phone}</p><div className="details"><div><span>Birthday</span><b>{user.birthday||"—"}</b></div><div><span>Filipino</span><b>{user.isFilipino?"Yes":"No"}</b></div><div><span>Account ID</span><b>{user.id||"—"}</b></div></div><button className="danger" onClick={onLogout}>Log Out</button></Shell>}

export function Activity({user,onBack}){const [items,setItems]=useState([]),[loading,setLoading]=useState(true);useEffect(()=>{let ok=true;(async()=>{try{if(auth.currentUser){const q=query(collection(db,"transactions"),where("userId","==",auth.currentUser.uid),limit(50));const s=await getDocs(q);if(ok)setItems(s.docs.map(d=>({id:d.id,...d.data()})));}}catch{}finally{if(ok)setLoading(false)}})();return()=>{ok=false}},[]);return <Shell title="Activity" icon="▤" onBack={onBack}><h1>Recent Activity</h1>{loading?<p>Loading...</p>:items.length?<div className="activity-list">{items.map(x=><div className="activity-row" key={x.id}><span>{x.type||"Transaction"}</span><b>₱{Number(x.amount||0).toLocaleString("en-PH",{minimumFractionDigits:2})}</b></div>)}</div>:<div className="empty"><strong>No transactions yet</strong><span>Your recent activity will appear here.</span></div>}</Shell>}
